### ISSUE TITLE
Think of a better name

### ISSUE THREAD

**Issue by aclissold** [Hoodbluck/authum-doc#5]
Nobody will want to use "cantaloupe," nor will they remember what it does! We should think of a name that is:
- Unambiguously pronounceable
- Short & easy to remember
- Possibly punny

We can use this issue as a brainstorming area.

**Comment by aclissold** [comment]
Oauthith?

![Oasis](http://mainepolicy.org/wp-content/uploads/oasis-400x250.jpg)

**Comment by aclissold** [comment]
Certify! Verificate?

**Comment by rastadrian** [comment]
Oauthith, lmao

**Comment by aclissold** [comment]
![Authum](https://cloud.githubusercontent.com/assets/4397642/8714143/8814a7ec-2b3f-11e5-91dd-0f96fce7436a.png)

**Comment by aclissold** [comment]
We might have to write it in Lithp at thith rate

**Comment by rastadrian** [comment]
I'm sold with Authum <3

**Comment by rastadrian** [comment]
@aclissold what does "Unambiguously pronounceable" means?

**Comment by aclissold** [comment]
It's entirely too many syllables way of saying I don't like words like "read" cause it could be red or reed
